# Generated by Django 5.2.3 on 2025-06-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('semestre', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('estudiando', 'Estudiando'), ('retirado', 'Retirado')], max_length=10)),
                ('razon_retiro', models.TextField()),
                ('historial_criminal', models.BooleanField()),
                ('situacion_economica', models.CharField(max_length=255)),
                ('condicion_especial', models.TextField(help_text='Estudios, discapacidades o enfermedades')),
            ],
        ),
    ]
