# Generated by Django 5.2.3 on 2025-06-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='condicion_especial',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='discapacidad_o_enfermedad',
            field=models.TextField(blank=True),
        ),
    ]
